# Setup
title:               Tensorlabbet
tagline:             'A blog of deep learnings'
description:         '<b>Tensorlabbet</b> presents a captivating blog spanning projects, reviews and unsolicited opinion pieces on the state of artificial intelligence research in academia and the industry'
url:                 https://tensorlabbet.com
baseurl:             ''
permalink:           /:year/:month/:day/:title/

# About/contact
author:
  name:              Taro Langner
  url:               tensorlabbet.com
  email:             taro.langner [at] tensorlabbet.com

# Custom vars
version:             1.1.0
